### ISSUE TITLE
Init concept prototype

### ISSUE THREAD

**Issue by mrpunkdasilva** [codigocerto/TrilhaFrontEndJR-JUN15#2]

**Comment by MrNullus** [comment]
## Brainstorm: 

-  Colocar um hero tomando 100% da tela, talvez uns 90%, 
    -  com isso nela vai ter minha foto  e  plano de fundo preto
    -  o nick em baixo da foto, com um efeito neon
-  Colocar seções separando as partes, e coloca uma imagens de IA  de acordo com algumas palavras chaves usando o bing

**Comment by MrNullus** [comment]
## Requisitos
- [ ]  Foto: Incluir uma foto pessoal.
- [ ]  Informações Pessoais: Nome completo e idade.
- [ ]  Sobre: Descrição pessoal, incluindo objetivos de carreira, áreas de interesse na programação, entre outros.
- [ ]  Gostos Pessoais: Liste ou descreva seus gostos pessoais de uma maneira que mostre sua criatividade e paixões. 
- [ ]  Motivações: Explique sua motivação em querer participar da comunidade Codigo Certo Coders
